version: '3.9'

services:
  jublia_app:
    container_name: jublia_app
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db, redis

  db:
    container_name: db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server
    ports:
     - '6379:6379'
  
  celery:
    build: .
    container_name: celery
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    command: celery -A run.celery worker --pool=gevent --concurrency=100 --loglevel=info
    depends_on:
      - redis
  
  
volumes:
  pgdata: {}
